from .Profession import Profession
from .Department import Department
from .Role import Role
from .Group import Group
from .User import User
from .Session import Session
from .Subject import Subject
from .GroupSubject import GroupSubject
from .Schedule import Schedule
from .ScheduleParam import ScheduleParam
from .Journal import Journal
from .Report import Report
from .GroupTutor import GroupTutor
from .DepartmentPresident import DepartmentPresident
