networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: "./backend"
    networks:
      - dev
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build:
      context: "./frontend"
    networks:
      - dev
    dns:
      - 8.8.8.8
      - 8.8.4.4
