# networks:
#   dev:
#     external: true

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: "./backend"
    network_mode: "host"

  frontend:
    build:
      context: "./frontend"
    network_mode: "host"
