services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - network

  backend:
    build:
      context: "./backend"
    networks:
      - dev

  frontend:
    build:
      context: "./frontend"
    networks:
      - network

networks:
  network:
    driver: bridge
